=== Klozz/TheXPerienceProject/ota.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:complexType name="DeviceType">
		<xsd:annotation>
			<xsd:documentation>Device</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Comment" type="xsd:anySimpleType" minOccurs="0"/>
			<xsd:element name="Filename" type="xsd:anySimpleType"/>
			<xsd:element name="DownloadUrl" type="xsd:anyURI"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ReleaseChannel">
		<xsd:annotation>
			<xsd:documentation>release template</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Stable" type="ReleaseChannelType"/>
			<xsd:element name="Testing" type="ReleaseChannelType" minOccurs="0"/>
			<xsd:element name="Experimental" type="ReleaseChannelType" minOccurs="0"/>
			<xsd:element name="Old" type="ReleaseChannelType" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ReleaseChannelType">
		<xsd:annotation>
			<xsd:documentation>basic elements</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="falcon" type="DeviceType" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="XPerienceOTA" type="ReleaseChannel"/>
</xsd:schema>

=== Klozz/TheXPerienceProject/ota_lollipop.xml
<?xml version="1.0" encoding="UTF-8"?>
<XPerienceOTA xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ota.xsd">
        <Stable>
        <falcon>
                        <Filename>9.0.2_r1-20150224-NIGHTLY-falcon</Filename>
                        <DownloadUrl>https://s.basketbuild.com/devs/klozz/XPerience-rom/falcon</DownloadUrl>
        </falcon>
        <ghost>
                        <Filename>9.1.1_r33-20160117-NIGHTLY-ghost</Filename>
                        <DownloadUrl>https://s.basketbuild.com/devs/klozz/XPerience-rom/ghost</DownloadUrl>
        </ghost>
        </Stable>
</XPerienceOTA>
